### ISSUE TITLE
merging asch-docs-site/source/dapp into asch/docs

### ISSUE THREAD

**Issue by yanyiwu** [AschPlatform/asch#109]
> Dear @yanyiwu
> 
> What are your plans for the documentation?
> Asch has several dapp documents that I find should be improved. [Link](https://github.com/AschPlatform/asch-docs-site/tree/master/source/dapp). Can we also merge them into the asch/docs main repository?
> 
> My suggestion would be that you update the chinese version and I do and english and german translation.
> 
> I would be happy to hear your thoughts on this :-)
> 
> Kind regards
> a1300

good idea, but i thought we already did it on [pr](https://github.com/AschPlatform/asch-docs/pull/17/commits/4c20bf45ef703b646123170ded2ec623a36407a2) , 
and now i am wondering why it is missing ? 
and i think it is better to open a new issue for that. 

copied from [issue 104](https://github.com/AschPlatform/asch/issues/104)

**Comment by yanyiwu** [comment]
@a1300 here.

**Comment by a1300** [comment]
Dear @yanyiwu 

I think not all documents were copied over. The following documents are missing:
``2_asset.md``
``3_mini_dao.md``
``4_dice_game.md``
``5_publish.md``
``index.md``
``assets (directory)``

I think it this documents need to be revised. After that I will make an english and german translation :-)

Kind regards
a1300
