### ISSUE TITLE
在创建区块时如何解决提议（propose）被堵塞引发的问题

### ISSUE THREAD

**Issue by meilongwhpu** [AschPlatform/asch#115]
在创建区块B时，要广播propose，若此时有待确认的区块A正在等待投票信息，如果由于某些原因，导致区块A的投票一直未达到三分之二，则导致区块B的投票信息无法被接收并处理，从而直接丢弃收到的区块B的投票信息。那么这个故障如何容错呢？若区块A创建成功了，但是区块B的投票信息被大量抛弃了，则区块B的投票信息如何重新获取呢？

**Comment by ByCnck** [comment]
他会停摆，区块高度不再增加，类似股市的熔断，但不会出现分叉。因为收集不到足够的票，没法产块，那么这个产块收集票数的过程就会一直持续，直到满足条件产生新块，b块如果出现问题也是一样的过程。
一般网络极差才会出现你说的情况，目前没有发生过，这种情况下可以认为互联网瘫痪了

**Comment by ByCnck** [comment]
这一过程就是dpos基础上加的部分pbft特性

**Comment by ByCnck** [comment]
还有个问题，你在QQ群里提的
还有个问题，顺便帮我解答下吧，在创建区块选择受托人时，是在受托人列表中从当前时段周期%101开始，逐步往后查找，找到为止；但是在验证的时候，仅仅是从受托人列表中取区块的时段周期%101位置的受托人来验证是否一致，这个不一致的概率很大吧

**Comment by ByCnck** [comment]
出现过不一致的情况，但原因是当时有部分账户余额不一致，涉及到块回滚。投票决定了受托人的排名，也就是出块顺序，只要相关账户的余额一致，投票信息就一致，那么出块及验证就没问题。改过块回滚的相关逻辑后没有再出现受托人验证不一致的情况。
