### ISSUE TITLE
注册合约地址传什么

### ISSUE THREAD

**Issue by luckyhua** [AschPlatform/asch#120]
### Version
1.3.5

### Environment
ubuntu 16.04

### Steps to reproduce

![image](https://user-images.githubusercontent.com/9531587/35800563-475c2f08-0aa4-11e8-9ead-ab75ed7c30ae.png)

### What is expected?

注册dapp合约的address代表什么，不是用户的钱包地址吗？传入用户的钱包地址报错
![image](https://user-images.githubusercontent.com/9531587/35800656-8bb97278-0aa4-11e8-8e42-aac9f62e5f13.png)

**Comment by ByCnck** [comment]
domain.js的第9行改成       suffix: address.split('.').pop()

**Comment by ByCnck** [comment]
也可以用interface中定义的接口去查询
```
// interface/domain.js中的定义
app.route.get('/domain/:address',  async function (req) {
    return await app.model.Domain.findOne({address: req.params.address})
})
```

```
http://192.168.2.245:4096/api/dapps/48ebd765d7353f5dcba1bcd01e842698e8a53c3b1b5ed6a035d458f2c6958dc8/domain/ADcfnbP9Mk4Mtan1VgLyu8qWDHtMrsTNq4
// 返回结果
{
	address: "baidu.com",
	ip: "",
	owner: "ADcfnbP9Mk4Mtan1VgLyu8qWDHtMrsTNq4",
	suffix: "com",
	success: true
}
```

**Comment by ByCnck** [comment]
1001合约，接收2个参数address和ip，所以输入两行
```
baidu.com
220.181.57.216
```

**Comment by ByCnck** [comment]
该demo中的另一个查询api，按照域名后缀进行查询
```
http://192.168.2.245:4096/api/dapps/48ebd765d7353f5dcba1bcd01e842698e8a53c3b1b5ed6a035d458f2c6958dc8/domain/suffix/com
// 返回结果
[{
	address: "baidu.com",
	ip: "220.181.57.216",
	owner: "ADcfnbP9Mk4Mtan1VgLyu8qWDHtMrsTNq4",
	suffix: "com"
}]
```

**Comment by luckyhua** [comment]
@ByCnck 代码明白了，语义没明白，请教下address填域名是何意，这块我一直以为是钱包的地址，很容易让人误解的。

**Comment by yanyiwu** [comment]
Adress在区块链项目里面确实容易误会，或许需要填域名或者ip的变量我们可以取名叫host如何哈？

**Comment by luckyhua** [comment]
@yanyiwu 嗯嗯，变量语义明确容易理解，这表名也是domain，这函数的语义是把域名写到库里面，我完全理解错误了，O(∩_∩)O哈哈~
