### ISSUE TITLE
Reading Asch Source Code / Asch源码阅读笔记

### ISSUE THREAD

**Issue by yanyiwu** [AschPlatform/asch#122]
[Asch源码阅读:启动过程概述](https://bbs.asch.io/topic/4200/asch%E6%BA%90%E7%A0%81%E9%98%85%E8%AF%BB-%E5%90%AF%E5%8A%A8%E8%BF%87%E7%A8%8B%E6%A6%82%E8%BF%B0)

**Comment by yanyiwu** [comment]
[Asch源码base模块基础之共识](https://bbs.asch.io/topic/4242/asch%E6%BA%90%E7%A0%81base%E6%A8%A1%E5%9D%97%E5%9F%BA%E7%A1%80%E4%B9%8B%E5%85%B1%E8%AF%86/1)

**Comment by a1300** [comment]
That are great articles. I would be happy to see this added to the documentation as **Asch Deep Dive** :-)

**Comment by yanyiwu** [comment]
yeah we are thinking about that .

**Comment by yanyiwu** [comment]
@a1300 now we have already created a private (because of some issue about publishing) repo for a new book about asch&dapp. 
and after finishing it, it will be open-sourced.

**Comment by a1300** [comment]
@yanyiwu  Cool 👍
Will the book be on english?

**Comment by yanyiwu** [comment]
@a1300 no, sorry, we only write Chinese on the first version of this book.

**Comment by yanyiwu** [comment]
[Asch源码base模块之Account](https://bbs.asch.io/topic/4406/asch%E6%BA%90%E7%A0%81base%E6%A8%A1%E5%9D%97%E4%B9%8Baccount)

**Comment by a1300** [comment]
@yanyiwu ok :+1:
It would be great to have the book after the Chinese publication translated into english

**Comment by yanyiwu** [comment]
[Asch源码base模块之transaction](https://bbs.asch.io/topic/4471/asch%E6%BA%90%E7%A0%81base%E6%A8%A1%E5%9D%97%E4%B9%8Btransaction)

**Comment by yanyiwu** [comment]
[Asch源码core模块之loader启动](https://bbs.asch.io/topic/4550/asch%E6%BA%90%E7%A0%81core%E6%A8%A1%E5%9D%97%E4%B9%8Bloader%E5%90%AF%E5%8A%A8)

**Comment by yanyiwu** [comment]
[Asch源码core模块之blocks](https://bbs.asch.io/topic/4559/asch%E6%BA%90%E7%A0%81core%E6%A8%A1%E5%9D%97%E4%B9%8Bblocks/1)

**Comment by yanyiwu** [comment]
[Asch源码core模块之transactions](https://bbs.asch.io/topic/4662/asch%E6%BA%90%E7%A0%81core%E6%A8%A1%E5%9D%97%E4%B9%8Btransactions/1)

**Comment by yanyiwu** [comment]
[Asch源码core模块之accounts](https://bbs.asch.io/topic/4699/asch%E6%BA%90%E7%A0%81core%E6%A8%A1%E5%9D%97%E4%B9%8Baccounts)

**Comment by yanyiwu** [comment]
[Asch源码core模块之delegates](https://bbs.asch.io/topic/4773/asch%E6%BA%90%E7%A0%81core%E6%A8%A1%E5%9D%97%E4%B9%8Bdelegates)
