### ISSUE TITLE
asch-cli命令注册dapp时报错

### ISSUE THREAD

**Issue by meilongwhpu** [AschPlatform/asch#124]
版本：asch v1.3.4，运行在docker上，
本地访问地址：http://127.0.0.1:17001
在注册dapp时执行如下命令：
asch-cli registerdapp -f dapp.json  -e "....................."
提示错误信息：
Error connect econnrefused 127.0.0.1:4096

**Comment by ByCnck** [comment]
https://github.com/AschPlatform/asch/issues/90
