### ISSUE TITLE
如何自定义dapp内部转账收取的手续费资产类型

### ISSUE THREAD

**Issue by linbian** [AschPlatform/asch#125]
在文档[Dapp核心开发流程解析.md](https://github.com/AschPlatform/asch/blob/master/docs/dapp_docs/Dapp%E6%A0%B8%E5%BF%83%E5%BC%80%E5%8F%91%E6%B5%81%E7%A8%8B%E8%A7%A3%E6%9E%90.md)中看到，Dapp可以自定义内部转账手续费收取的资产类别与数量【甚至不收取手续费】，但不知该如何设置。

**Comment by linbian** [comment]
同时系统默认情况下，内部转账使用的0.1XAS，是给了谁了呢？主链的记账委托人？还是DAPP的记账委托人节点呢？

**Comment by ByCnck** [comment]
Q1: 这个问题文档中有，建议把相关的文档都大致浏览一遍，然后就知道去哪里找答案
https://github.com/AschPlatform/asch/blob/master/docs/asch_sdk_api.md#84-appregisterfeetype-min-currency
https://github.com/AschPlatform/asch/blob/master/docs/asch_sdk_api.md#86-appsetdefaultfeemin-currency

Q2: 侧链(DAPP)的记账人
