### ISSUE TITLE
Asch dapp默认接口文档3.1.1.2 调用注释是否为转账?

### ISSUE THREAD

**Issue by duanzhichao** [AschPlatform/asch#128]
### Asch dapp默认接口文档3.1.1.2
    请求示例：
       var aschJS = require('asch-js');   
       ....
       // 将上面生成的“提现”交易数据通过post提交给asch server 

  上面提现是否为转账?

**Comment by eagleHovering** [comment]
提现不同于转账，提现是从DApp内部转到Asch链上的操作，
