### ISSUE TITLE
在线钱包问题反馈

### ISSUE THREAD

**Issue by gbt123** [AschPlatform/asch#137]
在线钱包：
1、强制备份和验证密钥。
在我加入的一些与阿希有关的群里面，经常有这样的用户，他们退出再登录后，币没了、地址变了。懂的人都知道这是怎么回事，但这些丢币用户是这样想的：
阿希团队黑吃我的币，我要不要报警？（来自阿希官方论坛的两个案例）
我只申请过一次钱包，怎么退出后重新登录币就没了，地址也变了？（来自论坛和qq群、微信群的众多案例）
这些都是用户自己的问题，没有保存好密钥，或者密钥记录错误，但因为用户自身认知问题，他会坚持这是阿希的问题！
解决这个问题的方法很简单，创建钱包时生成私钥txt文件，必须保存到本地；生成keystone文件+密码防护；通过技术手段确认用户已经保存正确密钥后才允许退出。包括但不限于：创建钱包后验证密钥时必须手动逐条输入助记词，禁止粘贴；通过浏览器cookie记录用户登录次数，如果是首次登录，必须强制验证密钥成功后才可以注销。

2、显示详细的错误信息。
目前所有错误信息均显示为“服务器错误”，这个细节是很负面的。会提高新手操作门槛，增加客服压力，并且对某些操作模糊不清。
错误信息应该简短而明确的告知用户哪里出错了，及提供解决建议。

3、特定资产的交易记录
目前资产概况只有转账功能，而操作记录却是全部资产的交易记录，无法筛选。建议增加特定资产的交易记录查询功能。

4、降低交易手续费
降低手续费可以提高市场活跃程度，提高交易量和流通率。

5、不要显示空白信息
如果某项目的记录是0，建议将这项记录在页面上用“无记录”显示出来，如果显示空白用户会不知道到底是没有，还是暂时没加载出来；对于正在加载的内容，显示“加载中”。

6、受托人搜索
A要给B投票，却需要找半天实在太麻烦，有个查找受托人功能就轻松多了。

**Comment by eagleHovering** [comment]
感谢您细致的建议，我们在新版的客户端中已有所改善，后续会不断完善。再次感谢您的支持！ @gbt123

**Comment by CaosBad** [comment]
团队已经根据 1.4 版本重做了客户端，我们会在新的版本迭代中，考虑您的建议。
