### ISSUE TITLE
use travis-ci to do auto testing?

### ISSUE THREAD

**Issue by yanyiwu** [AschPlatform/asch#14]
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

I will propose a pull request for that.

**Comment by sqfasd** [comment]
@yanyiwu 你能帮忙太好了，珍惜也在做这件事，他知道如何部署多节点，以及dapp。目前的test目录只是测单节点的基本功能
@ByCnck

**Comment by yanyiwu** [comment]
@sqfasd 目前 travis-ci 应该也只是提供基本的npm test自动跑测试而已哈，和zhenxi在做的应该是两码事。zhenxi那个应该是比较难一些，多节点测试啥的还是得靠zhenxi搞搞，travis-ci目前应该帮不上啥忙。

**Comment by sqfasd** [comment]
travis不是号称做持续集成的吗
应该可以在跑测试代码前启动一两个服务吧

**Comment by yanyiwu** [comment]
应该可以的。晚点我试试。

**Comment by yanyiwu** [comment]
在跑测试代码之前启动服务了。但是测试仍然没有通过（目前先在我自己账号上测试）： https://travis-ci.org/yanyiwu/asch/jobs/258145312
@sqfasd 有空看下符合预期吗？

**Comment by ByCnck** [comment]
符合预期，之前改过创世块，所有有些测试失效了，我近期会调整。AschPlatform/asch已加入到travis-ci

**Comment by sqfasd** [comment]
可能是一些接口不兼容导致，问题不大

**Comment by yanyiwu** [comment]
如果只是一些小问题，可以先把那些有问题的测试注释掉吧，至少先让测试整个跑passing了。省的每次提交代码都邮件报警说error了。
