### ISSUE TITLE
Create Gitter Asch Chatroom (Request)

### ISSUE THREAD

**Issue by a1300** [AschPlatform/asch#144]
Dear Asch-Team,

I would be happy if we can start a [gitter](https://gitter.im/) Chat-Room for developers. I would love to be a moderator.

Thanks in advance
Kind regards

**Comment by liangpeili** [comment]
Yes. Please invite me when you have done it.

**Comment by a1300** [comment]
I have thought that the Asch-Team creates the channel. So it is the official gitter-channel :-)

**Comment by a1300** [comment]
I created the following gitter channel: [asch-development](https://gitter.im/asch-development/Lobby)

Feel free to join
