### ISSUE TITLE
Hello World Dapp: login failed

### ISSUE THREAD

**Issue by hxzqlh** [AschPlatform/asch#149]
我照着 [Dapp开发教程一 Asch Dapp Hello World](https://github.com/AschPlatform/asch/blob/master/docs/dapp_docs/1_hello.md)说明，运行 `asch-cli dapps -a`命令后，拷贝 `asch-test-dapp` 到 `dapps/29da098c1b66fb109d9736c2beba9fca6be849782061332cec0e292a1ad896f7`  下面,更新了 `config.json` 里面的 `secret` 配置。

部署好 localnet 和 helloworld dapp 后，访问 dapp 页面，点击 login 按钮报错。
![2018-03-09 12 01 34](https://user-images.githubusercontent.com/3350776/37189894-a42e0ca0-2391-11e8-9795-65dc7fa305c9.png)

还是说要用户自己去实现这个` login` 接口？

**Comment by liangpeili** [comment]
页面没找到。有运行注册应用这一步骤吗？

**Comment by hxzqlh** [comment]
自己 fix了，其实是个配置问题。

`config.json` 里面的  `secret`没有配置好， 每个 secret 都要用  `""`引起来，我当时是直接拷贝 `asch-cli crypto -g`生成的（secret用`''`引起来）。

btw，程序是否可以人性化点，发现配置不合法就报错啊？

**Comment by bassjobsen** [comment]
@hxzqlh please close your issue when it is fixed. Can we communicate in English?

**Comment by bassjobsen** [comment]
@hxzqlh, please also try the renewed English version; https://github.com/AschPlatform/asch/blob/master/docs/dapp_docs/1_hello_en.md, also see https://github.com/AschPlatform/asch/issues/203#issuecomment-402867561
