### ISSUE TITLE
travis-ci account

### ISSUE THREAD

**Issue by yanyiwu** [AschPlatform/asch#17]
麻烦 aschplatform 的管理员开个 travis-ci的账号，帮忙 aschplatform的github账号，然后仓库会自动同步过去。
目前travis 在 asch-cli和 asch-js已经加上，参考 https://github.com/AschPlatform/asch-js  README 最上方的一些图标。
有账号了以后才能把build跑通。

**Comment by liangpeili** [comment]
@yanyiwu 已使用管理员账号进行关联，使用自己的 Github 账号登陆就可以看到开放到 travis 的项目，有其他项目要开放到 travis 也请联系我

**Comment by yanyiwu** [comment]
多谢
