### ISSUE TITLE
model下定义新的数据模型失败

### ISSUE THREAD

**Issue by sunyezi** [AschPlatform/asch#171]
### Version

1.3.6

### Environment

Ubuntu 16.04

### Steps to reproduce

之前在model下定义过新的数据模型 成功。
3月27的时候在model下新建一个js文件（文件为空），提示dapp not ready，而且log中没有error。

**Comment by bassjobsen** [comment]
I can only confirm your issue. All files in the `model` should be valid and export a model; like:

```  
module.exports = {
  name: "test",
  fields: [
    {
      name: "recipientId",
      type: "String",
      length: 256,
      not_null: true,
      index: true
    }

```
When any file is invalid (or in many other situations) you'll get the `dapp is not ready` message without any debug message.
