### ISSUE TITLE
执行npm install报错

### ISSUE THREAD

**Issue by aoshiguchen** [AschPlatform/asch#181]
npm 版本: 6.0.0
node 版本: 8.1.2
操作系统: win10
![image](https://user-images.githubusercontent.com/10580997/39795892-f78af556-5385-11e8-8658-d836a36cc9a8.png)

**Comment by aoshiguchen** [comment]
> sodium@2.0.3 preinstall D:\myspace\git\asch\test1\node_modules\sodium
> node install.js --preinstall

Please set your Microsoft Visual Studio version before you run npm install
Example for Visual Studio 2015:

    For you user only:

        npm config set msvs_version 2015

    Global:

        npm config set msvs_version 2015 --global

Supported values are 2010, 2012, 2013, 2015

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@2.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-05-09T04_38_38_463Z-debug.log

**Comment by aoshiguchen** [comment]
我电脑没有装vs，这个跟vs有什么关系么

**Comment by ByCnck** [comment]
sodium需要编译安装，win下是vs，linux是gcc等。

**Comment by a1300** [comment]
Dear @aoshiguchen 

I honestly haven't tried this tutorial myself. But there is a [tutorial for the asch windows-installation](https://github.com/AschPlatform/asch/blob/master/docs/asch_dev_windows_install.md)

Did you used this tutorial?

Kind regards
a1300
