### ISSUE TITLE
对于多重签名账号参与的交易，在交易数据的签名和验证部分发现一个疑点

### ISSUE THREAD

**Issue by meilongwhpu** [AschPlatform/asch#183]
发现一个疑问，烦请确认是否为bug？
在交易数据的签名过程中，对于多重签名账号参与的交易，在二次签名之前，校验的是多重签名账号是否存在二级密码；代码如下（base/transaction.js的create方法）：
  if (data.sender.secondSignature && data.secondKeypair) {
    trs.signSignature = this.sign(data.secondKeypair, trs);
  }

在交易数据的签名验证过程中，对于多重签名参与的交易，校验的是请求者账号是否存在二级密码；代码如下（base/transaction.js的verify方法）：
else if (trs.requesterPublicKey && requester.secondSignature) {
    try {
      var valid = this.verifySecondSignature(trs, requester.secondPublicKey, trs.signSignature);
    } catch (e) {
      return setImmediate(cb, e.toString());
    }
    if (!valid) {
      return setImmediate(cb, "Failed to verify second signature: " + trs.id);
    }

**Comment by sqfasd** [comment]
https://github.com/AschPlatform/asch-core/blob/develop/src/base/transaction.js#L140
https://github.com/AschPlatform/asch-core/blob/develop/src/base/transaction.js#L295
https://github.com/AschPlatform/asch/blob/develop/src/contract/group.js
已通过group合约来解决多重签名的问题了
