### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by bassjobsen** [AschPlatform/asch#184]
### Version
1.3.6

### Environment

ubuntu 14.04

### Steps to reproduce
it runned once, but now i'm not able to start it

### What is expected?
deamon keeps running

### What is actually happening?
deamon stops

**Comment by liangpeili** [comment]
Can you find a asch.pid  file in the asch folder?

**Comment by bassjobsen** [comment]
@liangpeili thanks for your reply!
I tried again on unbuntu 16.04 now the deamon keep running and a `asch.pid`.

New issues:
`grep Forging logs/debug.log` returns nothing and `grep Failed logs/debug.log` returns the following:

`{"level":"error","message":"Failed to load delegates","timestamp":"2018-05-24 14:33:42 401","data":"Account 4fee21b5945b4553f0af641a9fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx not found"}`

**Comment by a1300** [comment]
Hello @bassjobsen
 
Which asch-node did you download?
1. Did you clone this repository with `git clone https://github.com/AschPlatform/asch`. (Document: [Start developing Dapps](https://github.com/AschPlatform/asch/blob/master/docs/dapp_docs/1_hello_en.md))
2. Or did you downloaded the latest mainnet with the following command?(Document [Install asch-node](https://github.com/AschPlatform/asch/blob/master/docs/asch_install_en.md))
```bash
wget https://www.asch.io/downloads/asch-linux-latest-mainnet.tar.gz
tar zxvf asch-linux-latest-mainnet.tar.gz
```

I would like to understand your ultimate goal (so we can better help you :-) ). Do you want to run a asch-node as a delegate on a server or do you want to develop decentralized apps (Dapps)?

I am looking forward to your answer :-)
Kind regards
a1300

**Comment by bassjobsen** [comment]
Hi @a1300,

Thanks for you're reply. I did downloaded the latest mainnet and would like to run a asch-node as a delegate.

Node version: v8.10.0

I didn't found the English instructions before. Now i do understand that the problem can be: your account has not been registed as delegates.

You can find my delegate register here: https://explorer.asch.io/searchResult.html?q=A9tAWBJYDLpvbgPsSVC4ZE89dKAPXoFJ7m

Thank you very much!

**Comment by a1300** [comment]
Hello @bassjobsen 

No problem :-)
Is everything working for you so far?

Kind regards
a1300

**Comment by bassjobsen** [comment]
hi @a1300,

The deamon runs, but the logs tell me:

`{"level":"error","message":"Failed to load delegates","timestamp":"2018-05-25 09:07:28 776","data":"Account 4fee21b5945b4553f0af641a9fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx not found"}
`
For security i've replaced some chars in the account address with x's.
I'm don't know that address. My address is A9tAWBJYDLpvbgPsSVC4ZE89dKAPXoFJ7m?

**Comment by a1300** [comment]
I don't fully understand your problem...

Every account following properties:
* An Address of type
    * `14762548536863074694` (old format) 
    * Or `AHMCKebuL2nRYDgszf9J2KjVZzAw95WUyB` (new format) 
* An secret (or password): 
    * `someone manual strong movie roof episode eight spatial brown soldier soup motor`
        * (bip39 complient, like bitcoin)
* An keypair
    *  PublicKey `8065a105c785a08757727fded3a06f8f312e73ad40f1f3502e0232ea42e67efd`
     * PrivateKey `a64af28537545301f66579604628b55c7a7a102752bbd8f0b0d152f9754e78d58065a105c785a08757727fded3a06f8f312e73ad40f1f3502e0232ea42e67efd`

1. Did you enabled your secret with `./aschd enable "your sercret"`
    * The secret must have a format of 
2. Did you wrote your secret into `config.json` like in the [Tutorial](https://github.com/AschPlatform/asch/blob/master/docs/asch_install_en.md)?
     * Like on the picture
3. Did you restarted your asch-node with `./aschd restart` ?

Looking forward to your answer :-)

Kind regards
a1300

**Comment by bassjobsen** [comment]
i didn't run the `enable` comammand before because of i thought i've edit the secret in the `config.json` already.
But when i run the command with my sectrect the deamon returns:

`{"success":false,"error":"Delegate not found"}`

So i seems the problem is i'm not registered as Delegate yet

PS how to find my private key, when using the online wallet?

**Comment by a1300** [comment]
I checked, you are registered as delegate on the mainnet. 
`http://mainnet.asch.io/api/delegates/get?username=bassjobsen`

It is possible that your local blockchain is not fully synced?
You could run `./aschd rebuild`

Try to run the following command, to see continuous log-output: `tail -f logs/debug.log`

Kind regards
a1300

PS Normally you don't need your private key. The `secret` is enough. You can get the public and private-key from your secret with [asch-js]
See [asch-cli/crypto.js file](https://github.com/AschPlatform/asch-cli/blob/master/lib/crypto.js)
```
var keypair = function (secret) {
	var hash = crypto.createHash('sha256').update(secret, 'utf8').digest();
	var kp = nacl.crypto_sign_keypair_from_seed(hash);

	var keypair = {
		publicKey: new Buffer(kp.signPk).toString('hex'),
		privateKey: new Buffer(kp.signSk).toString('hex')
	}

	return keypair;
}
```

**Comment by bassjobsen** [comment]
Hi,
I ran the rebuild. It returned the following:

```
blockchain-mainnet-snapshot.tar.gz  100%[=================================================================>]   1,46G  1,12MB/s    in 12m 48s 

2018-05-25 13:31:17 (1,94 MB/s) - ‘blockchain-mainnet-snapshot.tar.gz’ saved [1564007135/1564007135]

Check md5 passed!
Asch server is not running


mv: './blockchain.db' and './blockchain.db' are the same file
Asch server started as daemon ...
```
The `the same file` suggests that it was uptodate already?

The `enable` command now returns:

`{"success":false,"error":"Blockchain is loading"}`

`cat logs/debug.log`:
 
```
{"level":"log","message":"Asch started: 0.0.0.0:8192","timestamp":"2018-05-25 11:38:47 893"}
{"level":"log","message":"Asch started: 0.0.0.0:8192","timestamp":"2018-05-25 11:40:55 912"}
{"level":"info","message":"Modules ready and launched","timestamp":"2018-05-25 11:41:03 591"}
```
So i do have to wait now?

**Comment by bassjobsen** [comment]
`cat logs/asch_monitor.log` gives:

```
25 May 13:59:12 ntpdate[19357]: adjust time server 5.79.108.34 offset 0.002020 sec
2018-05-25 14:00:02[error]	Asch server is not running and restarted
25 May 14:00:11 ntpdate[19706]: adjust time server 5.79.108.34 offset -0.000472 sec
2018-05-25 14:01:03[error]	Asch server is not running and restarted
25 May 14:01:12 ntpdate[20047]: adjust time server 5.79.108.34 offset 0.000352 sec
2018-05-25 14:02:03[error]	Asch server is not running and restarted
25 May 14:02:12 ntpdate[20461]: adjust time server 82.94.235.106 offset -0.002831 sec
2018-05-25 14:03:03[error]	Asch server is not running and restarted
25 May 14:03:11 ntpdate[20852]: adjust time server 194.171.167.130 offset -0.000557 sec
2018-05-25 14:04:02[error]	Asch server is not running and restarted
25 May 14:04:11 ntpdate[21291]: adjust time server 46.243.26.34 offset -0.002585 sec
```

**Comment by bassjobsen** [comment]
Okay now it seems to work!

```
{"level":"info","message":"Blockchain ready","timestamp":"2018-05-25 12:13:34 677"}
{"level":"info","message":"start to launch 0 installed dapps","timestamp":"2018-05-25 12:13:39 641"}
{"level":"info","message":"Forging enabled on account: A9tAWBJYDLpvbgPsSVC4ZE89dKAPXoFJ7m","timestamp":"2018-05-25 12:13:39 753"}
```
The next question is how to reach the to 101?

**Comment by bassjobsen** [comment]
Thanks you very much. Yes, i've seen your previous comment :) I'll take a look at the OS awards coming days!

**Comment by a1300** [comment]
Ok :-)
Please let me know if you have some questions!

If you have some points of criticism or ideas for improvement. Please tell us. There are many things that could be better. I always like to hear some opinion from outside :-)

**Comment by bassjobsen** [comment]
@a1300 i'll let you know. Thanks.
Last question for know.
Keep running the node now, makes no sense?

**Comment by a1300** [comment]
@bassjobsen  I send you an email
