### ISSUE TITLE
July 2018 Google Chrome starts to display SSL warnings

### ISSUE THREAD

**Issue by a1300** [AschPlatform/asch#191]
Dear Asch-Team,

according to this [Google Blog Post](https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html) Google Chrome will start with July 2018 to mark website that are still using __http__ as __<span style="color:red">not secure</span>__.

[mainnet.asch.io](http://mainnet.asch.io/#/login) will be marked as not secure and I think most delegate nodes will be also marked as not secure. 

I don't want, that users will loose trust in the Asch platform.

Kind regards
a1300

**Comment by liangpeili** [comment]
@a1300 We offer two https sites: https://wallet.asch.cn       https://mainnet.asch.io
