### ISSUE TITLE
api errors

### ISSUE THREAD

**Issue by ByCnck** [AschPlatform/asch#195]
### Version
1.3.6

### Environment
linux

### Steps to reproduce
频繁访问（比如每秒2次）可能会返回空值。
/api/blocks
payload = {'generatorPublicKey': publickey,'limit': 1,'orderBy': 'height:desc'}
// 返回结果为success，但内容为空
{u'count': 0, u'blocks': [], u'success': True}

**Comment by bassjobsen** [comment]
@bigBron how to reproduce this issue? When i call the api with `curl` i do not find these failures?

**Comment by eagleHovering** [comment]
It fixed in v1.4.1
