### ISSUE TITLE
大家有没有遇到这个问题

### ISSUE THREAD

**Issue by 709594501** [AschPlatform/asch#196]
### Environment
![image](https://user-images.githubusercontent.com/30765850/41243872-faa70c10-6dd5-11e8-99af-7c57f6cfef68.png)

**Comment by a1300** [comment]
Hello @709594501 

do you have the linux package `sqlite3` installed?
Please try to run the command `which sqlite3` in the linux-konsole. The result should be `/usr/bin/sqlite3`

If the `sqlite3` linux-package is not installed please install it.
`sudo apt-get install curl sqlite3 ntp wget git libssl-dev openssl make gcc g++ autoconf automake python build-essential -y
`

Let me know if that worked for you
Kind regards
a1300
