### ISSUE TITLE
如何部署dapp到mainnet上?

### ISSUE THREAD

**Issue by bigBron** [AschPlatform/asch#202]
Version 1.3.4
dapp开发文档没有给出最后如何发布到mainnet步骤
是自己搭建服务器节点还是？
dapp配置里面得受托人和节点受托人是同样得意思吗？

**Comment by sqfasd** [comment]
文档已迁移到https://github.com/AschPlatform/asch-docs
部署到mainnet与localnet一样，只要把register dapp的时候，注册到主网就行了，部署的时候使用主网节点进行部署
