### ISSUE TITLE
Why does dapp not read the balance?

### ISSUE THREAD

**Issue by bassjobsen** [AschPlatform/asch#203]
Hello,
When i run `http://localhost:4096/api/dapps/f220f47cce6d408c691e6625f6f38812cab16d48bd04367c4a7aa620fa127ab9/balances/AB52eKNVD1Z7gYGvJTV2KCoQKfuEpiJddy` i got the following result:

```
{"balances":[],"success":true}
```

So the balances are empty?

But `asch-cli -H 127.0.0.1 -P 4096 openaccount "page lava hammer shoulder renew slice alley index index call hold easily"` give me the following result:

```
{
  "address": "AB52eKNVD1Z7gYGvJTV2KCoQKfuEpiJddy",
  "unconfirmedBalance": 90000000000,
  "balance": 90000000000,
  "publicKey": "20db96eddce91df8d52e9db218ac74ca190acbc666487c999537ab6d1a8d2d61",
  "unconfirmedSignature": false,
  "secondSignature": false,
  "secondPublicKey": "",
  "multisignatures": [],
  "u_multisignatures": [],
  "lockHeight": 0
}
```
So the balances for AB52eKNVD1Z7gYGvJTV2KCoQKfuEpiJddy are not empty?

**Comment by bassjobsen** [comment]
@liangpeili thanks for your reply. I try to understand even when my Dapp balance shows 600 XAS (after made a deposit) the api call still returns empty.

Maybe i use the wrong wallets (or addresses)

First of all i register and install my Dapp (using asch-redeploy) which should refuel my balance. asch-redeploy uses the wallet with secret "sentence weasel match weather apple onion release keen lens deal fruit matrix".
Now i can go to http://localhost:4096/#/application and find my new installed Dapp, and check the balance (and do a deposit to it), see:

![balance](https://user-images.githubusercontent.com/954055/42280269-8da94e5c-7fa0-11e8-955b-4be8b5574fa7.png)

Then i go to the dapp and login with secret "sentence weasel match weather apple onion release keen lens deal fruit matrix" again, and find my balance empty

**Comment by a1300** [comment]
Dear @bassjobsen 

### asch-redeploy
[asch-redeploy](https://github.com/AschPlatform/asch-redeploy) is using the following account as its default master account to register all Dapps and send money to them:
```js
    address: AHMCKebuL2nRYDgszf9J2KjVZzAw95WUyB
    secret: sentence weasel match weather apple onion release keen lens deal fruit matrix
    publicKey: a7cfd49d25ce247568d39b17fca221d9b2ff8402a9f6eb6346d2291a5c81374c
```
You can __override__ this using your own account. 
```
asch-redeploy --master "page lava hammer shoulder renew slice alley index index call hold easily"
```
You need the newest version of asch-redeploy

### Info
The Dapp Balance in the GUI frontend is a sum over all Dapp accounts. It is not one account. You could download the  [SQLiteBrowser](https://sqlitebrowser.org/) or use [SQLiteOline](https://sqliteonline.com/#) to inspect your Dapp database file and see which account has the XAS. Your Dapp database file is located in `asch/dapps/dappId/blockchain.db`

### Common Problems - Does your Dapp produce blocks?
- You can check with `localhost:4096/api/dapps/dappId/blocks`
- If it doesn't produce blocks then it also hasn't processed the transaction
   - Be sure to have 5 delegate secrets in `config.json` stored



Please let me know if something didn't worked out...

**Comment by bassjobsen** [comment]
@a1300 thank you very much. At the end it seems that the 5 delegate secrets were missing indeed. Why does asch-redeploy not set these secrets?

**Comment by a1300** [comment]
@bassjobsen  no problem.
I will have a look why that happened.

Did you used some starterkit?

**Comment by bassjobsen** [comment]
Hi @a1300,

After installing Asch (`git clone https://github.com/aschplatform/asch.git asch && cd asch && npm install && cd ..`) i preform the following steps:

- `git clone https://github.com/AschPlatform/asch-redeploy.git && cd asch-redeploy && yarn install && cd ..`

- `git clone https://github.com/bassjobsen/asch-test-dapp.git && cd asch-test-dapp && ../asch-redeploy/bin/asch-redeploy`

After run the above step, i found that the `asch/dapp/<dappid>/config.json` file looks like that shown beneath:

```
{
	"secrets": [
		
	]
}
```

**Comment by a1300** [comment]
Hi @bassjobsen 

in the `dapp.json` file we provide a list of delegates public keys. These delegates will be used during the registration of our Dapp on the local blockchain. The secrets of these delegates are need to be stored in the `config.json` file in order to enable forging/block-production.

```js
...
"delegates": [
  "d1facb776188e7776810b2f1d048dfc5c049cfaaea71db06092990522298f0f0",
  "3a8ae68edd9a127a899365092a52778d03f1070a283e7cea1ad4efd83237602c",
  "3ac06b5f1fbc35c5debb44d402f7d540de077bb1f68089328cb24554aaeaba21",
  "d2c1508203415ea09b9197a7ccdcbdebf23ce6d7454ad21bfaa0c851f846f5b1",
  "5daba5f0774903c3504065a375099b5b9b0452f7d970f85ad433c8a01ce6c20e"
]
...
```

What we need to add to `config.json` are the 5 delegate secrets:
```js
{
  "secrets": [
    "flame bottom dragon rely endorse garage supply urge turtle team demand put",
    "thrive veteran child enforce puzzle buzz valley crew genuine basket start top",
    "black tool gift useless bring nothing huge vendor asset mix chimney weird",
    "ribbon crumble loud chief turn maid neglect move day churn share fabric",
    "scan prevent agent close human pair aerobic sad forest wave toe dust"
  ]
}
```

------------------------------
The 5 delegates are the ones we used in this [tutorial](https://github.com/AschPlatform/asch/blob/2c8df1f7acbc713dab1d2c2a93bbe31b31eb1836/docs/dapp_docs/1_hello_en.md#7-create-a-dapp-metadata-file).
```js
[ 
  { 
    address: 'AN1yKK47P3MtD5ZgHYoncGQ1gCn4p2vGAC',
    secret: 'flame bottom dragon rely endorse garage supply urge turtle team demand put',
    publicKey: 'db18d5799944030f76b6ce0879b1ca4b0c2c1cee51f53ce9b43f78259950c2fd' 
  },
  { 
    address: 'AGeeCmSVLDNbtMqqpJchQZakchwzpuje1P',
    secret: 'thrive veteran child enforce puzzle buzz valley crew genuine basket start top',
    publicKey: '590e28d2964b0aa4d7c7b98faee4676d467606c6761f7f41f99c52bb4813b5e4' 
  },
  { 
    address: 'A7NWaYUkpa543hdTsfw57AoZAgCBr2NFY6',
    secret: 'black tool gift useless bring nothing huge vendor asset mix chimney weird',
    publicKey: 'bfe511158d674c3a1e21111223a49770bee93611d998e88a5d2ea3145de2b68b'
  },
  { 
    address: 'ABU1G2pQFMGa7c1GiAPYCQuUhiPHdvCSB2',
    secret: 'ribbon crumble loud chief turn maid neglect move day churn share fabric',
    publicKey: '7bbf62931cf3c596591a580212631aff51d6bc0577c54769953caadb23f6ab00' 
  },
  { 
    address: 'AG1A3ojeLAMZySaZWTkg49jcoVCV7FCKXF',
    secret: 'scan prevent agent close human pair aerobic sad forest wave toe dust',
    publicKey: '452df9213aedb3b9fed6db3e2ea9f49d3db226e2dac01828bc3dcd73b7a953b4' 
  } 
]
```

**Comment by bassjobsen** [comment]
@a1300 thanks. Indeed. Can asch-redeploy write them automatically to `config.json`?

**Comment by a1300** [comment]
@bassjobsen that is a good idea :+1: 

I am thinking about how to do it. Either I will give out a warning message or write them directly to `config.json`
