### ISSUE TITLE
建议将bignumber作为utility接口，通过sdk提供的app.util.bignum提供，不需要require

### ISSUE THREAD

**Issue by sqfasd** [AschPlatform/asch#209]
### Version

develop

### Solution

1. 将https://github.com/AschPlatform/bignumber的源码直接放到asch-core的util目录
2. 在runtime.js中，通过app.util导出
3. 修改所有的require('bignumber')语句，包括asch、asch-core两个项目

**Comment by nswbmw** [comment]
第一步我觉得还是将 bignumber 单独成模块比较好，第二三步没问题

**Comment by sqfasd** [comment]
可以pullrequest
