### ISSUE TITLE
asch-sandbox does not found

### ISSUE THREAD

**Issue by anshuman-singh-93** [AschPlatform/asch#24]
on npm install npm giving error 404 for asch-sandbox

**Comment by yanyiwu** [comment]
Will be reopened along with the documents soon later, please be patient .

**Comment by MYanzhe** [comment]
on npm install npm giving error 404 for ascu-sandbox  How long will it take to visit?

**Comment by alexpro401** [comment]
And how install if not have asch-sandbox?

**Comment by sqfasd** [comment]
Fixed by using asch-sandbox-dist instead, which is an obfuscated version of asch-sandbox
