### ISSUE TITLE
log信息，换行符‘\n’并没有正确解释

### ISSUE THREAD

**Issue by zhangsanfeng1988** [AschPlatform/asch#26]
log信息，换行符‘\n’并没有正确解释，打印信息如下所示：
fatal 2017-08-31 06:27:32 978 init.js:410 Domain uia { message: 'Cannot find module \'complex.js\'',
  stack: 'Error: Cannot find module \'complex.js\'\n    at Function.Module._resolveFilename (module.js:489:15)\n    at Function.Module._load (module.js:439:25)\n    at Module.require (module.js:517:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/home/ouxb/asch/node_modules/mathjs/lib/type/complex/Complex.js:1:77)\n    at Module._compile (module.js:573:30)\n    at Object.Module._extensions..js (module.js:584:10)\n    at Module.load (module.js:507:32)\n    at tryModuleLoad (module.js:470:12)\n    at Function.Module._load (module.js:462:3)' }

**Comment by sqfasd** [comment]
后面会对代码进行一次重构，到时候会用一个更好用的log库
