### ISSUE TITLE
How to change the transaction fee

### ISSUE THREAD

**Issue by vpanwar821** [AschPlatform/asch#264]
Currently asch is charging 10000000 as a transaction fee but I want to reduce it to some 1% of the transaction amount in my platform . Can anyone help me with this as I am not able to find where it is setting the fees.

**Comment by a1300** [comment]
@vpanwar821 what do you mean with `my platform`?


## 1 If you are meaning your __Sidechain__ (or DApp)  
As far as I know, you can't set the transaction fee to `1%` on your sidechain. You can set the fee for a custom contract on the sidechain to a fixed value (documented [here](https://github.com/AschPlatform/asch-docs/blob/master/sdk_api/en.md#84-appregisterfeetype-min-currency))

## 2 If you mean the ASCH mainchain

The fee calculation does not happen in the main [asch](https://github.com/AschPlatform/asch) repo.

Change the following code in asch-core/src/utils/calculate-fee.js  
```js
 1: () => 0.1,
```

In https://github.com/AschPlatform/asch/issues/224 you can see the fee calculation and the contract names. You need to change contract `1` if you want to transfer `XAS`.

1. You would need to fork the [asch-core](https://github.com/AschPlatform/asch-core) repo
2. change the [asch-core/src/utils/calculate-fee.js](https://github.com/AschPlatform/asch-core/blob/c3eda1bf1b61ea8cf4feae5c240b46353b7248dc/src/utils/calculate-fee.js) file.
3. Push changes to https://github.com/vpanwar821/asch-core
4. Change package.json file in your downloaded [asch](https://github.com/AschPlatform/asch) repo to point to your updated asch-core version
```diff
- "asch-core": "https://github.com/AschPlatform/asch-core/tarball/v1.4.4",
+ "asch-core": "https://github.com/vpanwar821/asch-core",
```
5. Rebuild downloaded asch blockchain
