### ISSUE TITLE
Inconsistency of produced blocks by delegates 

### ISSUE THREAD

**Issue by liangpeili** [AschPlatform/asch#273]
api1: http://192.168.1.155:8192/api/v2/misc/blocksForgedBy?orderBy=timestamp:desc&limit=10&offset=0&name=united_asch&reverse=1

api2: http://192.168.1.155:8192/api/delegates/get?address=A9NjNaBVeQKE53DzGYaBMtT17b2F15GBi2

Produced blocks don't have the same number.

**Comment by chengenguan** [comment]
api1 has been deprecated.
