### ISSUE TITLE
将asch-frontend、asch-js、asch-cli作为asch的submodule以解决版本不同步问题

### ISSUE THREAD

**Issue by sqfasd** [AschPlatform/asch#38]

**Comment by yanyiwu** [comment]
是否也可以考虑直接把这些仓库代码融合进 asch 这个仓库呢？这样感觉 commit 更集中一些，否则 commit 都分散了，容易让人觉得 asch 更新不频繁。

**Comment by yanyiwu** [comment]
比如 asch-docs ，是否可以考虑一下直接作为  asch/docs 的目录存在呢？

**Comment by yanyiwu** [comment]
比如这样? https://github.com/AschPlatform/asch/pull/58 
供参考哈

**Comment by yanyiwu** [comment]
我看到docs和frontend都归并到asch了，目前感觉挺好的。话说大家对asch-cli打算怎么处置呢？个人感觉似乎也是可以作为asch里的子目录？

**Comment by ByCnck** [comment]
后面也会合进来，只是这次发版仓促没来得及弄其他几个

**Comment by eagleHovering** [comment]
下一步会重新设计模块和组件
