### ISSUE TITLE
UIA新增接口，根据指定资产返回交易记录

### ISSUE THREAD

**Issue by sqfasd** [AschPlatform/asch#42]
## 背景

原来的/api/uia/transactions/:address接口用于返回指定账户的所有资产操作记录
/api/uia/transfers/:address/:currency接口用于返回指定账户和制定资产的所有操作记录

## 需求说明

1. 这两个接口命名不太合理，可以合并到一个uri下，比如/api/uia/my/transactions
2. 需要新增一个根据指定资产返回资产操作记录的接口， 不限定账户了, /api/uia/transactions/:currency

**Comment by ByCnck** [comment]
/api/uia/transactions/:address 改名为 /api/uia/transactions/my/:address
/api/uia/transfers/:address/:currency 改名为 /api/uia/transactions/my/:address/:currency 
新增 /api/uia/transactions/:currency 

``` 备注：```带currency 关键字的接口只能查询转账记录，查不到资产注册、资产发行等信息。而/api/uia/transactions/my/:address这个是可以查询到资产注册、发行信息的。（有currency 时会与transfers表做等值关联，不能同时 issues进行关联。）

文档已更新：https://github.com/AschPlatform/asch-docs/blob/master/asch_http_interface.md#21012-获取指定资产转账记录

代码提交记录：https://github.com/AschPlatform/asch/commit/36731263b0a15b45b401f0f716643def06bb9d64

@sqfasd please review
