### ISSUE TITLE
区块同步在2865350就无法在增加了

### ISSUE THREAD

**Issue by nearcode** [AschPlatform/asch#47]
error 2017-10-29 06:41:48 078 app.js:9104 Failed to process block: Failed to verify transaction: Amount should be integer { id: '5df16ed548d8b7450ac0f31ffe5345ba930f29c4d7e6942f7856890c7f32f44f',
  version: 0,
  timestamp: 33051030,
  height: 2865351,
  previousBlock: '62820a89b6235cbad8fc325bfca179db0bec5d6fc1aac254fb970fbbedbf57a2',
  numberOfTransactions: 1,
  totalAmount: 0,
  totalFee: 50000000000,
  reward: 350000000,
  payloadLength: 263,
  payloadHash: '09319d25b0e219105500880a261710ace98188dbac9e9cbdbe13b8f02720da30',
  generatorPublicKey: 'd0ebf16dbf8701290d30ecd8527263f471cea8f98ee5657a22df4b5abce61da0',
  generatorId: '277484741189613089',
  blockSignature: 'fefb333fd75d00942d4d343034862a8934df862cdb4ad827e9fd028fddfc523fdbb2386e78f273bd223343e87b92a6506fac3ec2cbe5aaceaa1e320bed619305',
  totalForged: 50350000000,
  transactions:
   [ { id: '09319d25b0e219105500880a261710ace98188dbac9e9cbdbe13b8f02720da30',
       height: 2865351,
       blockId: '5df16ed548d8b7450ac0f31ffe5345ba930f29c4d7e6942f7856890c7f32f44f',
       type: 10,
       timestamp: 33051013,
       senderPublicKey: '7eaf284de9fd5d1d3505890c0f7361fe255c84acb8b6328704ecab1aebb54d25',
       requesterPublicKey: '',
       senderId: '9015597308060636230',
       recipientId: '',
       amount: 0,
       fee: 50000000000,
       signature: '3cd962577d601999e97213e66ed1c8d92a82b12ccef3c3d3f9a787454e79a4bcee3eac63ed74e4a6f9b56e8ab5665482a3f081180c072c467c4b0e3b8d1c8f0d',
       signSignature: 'ef346da41ad7f05baf283ad3307cd9b427193817f61c6c78d9d7a18f8996c689f20fd083f9d757ef73f1eaa5388cfe130dd353ab002a22355973ad06ae0cf706',
       message: '',
       asset: [Object] } ] }
error 2017-10-29 06:41:48 080 app.js:9105 Block 5df16ed548d8b7450ac0f31ffe5345ba930f29c4d7e6942f7856890c7f32f44f is not valid, ban 60 min 45.63.27.97:80

**Comment by ByCnck** [comment]
这个问题在我们之前的版本已升级解决，请用快照直接rebuild本地文件
```
cd Asch目录
curl -sL https://www.asch.so/downloads/rebuild-mainnet3.sh | bash
```
