### ISSUE TITLE
您好，咨询关于DAPP的问题

### ISSUE THREAD

**Issue by miewx** [AschPlatform/asch#5]
问几个
如果想基于这个开发一个去中心化的交易所
请问
1.  如何对接其他区块链（比特币、以太币等），有api吗？
2. 有给浏览器用的sdk吗？类似 https://github.com/LiskHQ/lisk-js

**Comment by ByCnck** [comment]
1、其它区块链的代币可以通过在Asch主链上发行用户资产来实现，比如miewx.btc和btc 1:1兑换。
交易所内可以交易Asch区块链的代币XAS和用户发行资产
2、Asch-JS，https://github.com/sqfasd/asch-js
