### ISSUE TITLE
wallet.asch.io

### ISSUE THREAD

**Issue by yanyiwu** [AschPlatform/asch#62]
这个钱包域名啥时候上？@liangpeili

**Comment by liangpeili** [comment]
还没定，不过随时可以上

**Comment by yanyiwu** [comment]
主要是还在等什么呢？是还没确定是否取名叫这个吗？

**Comment by yanyiwu** [comment]
感谢 @liangpeili 大佬辛苦，http://bbs.asch.io/topic/3402/%E9%98%BF%E5%B8%8C%E6%96%B0%E9%92%B1%E5%8C%85%E5%9C%B0%E5%9D%80https-wallet-asch-io-%E5%90%AF%E7%94%A8 已上线。
