### ISSUE TITLE
合约事务unsigned接口手续费设置问题

### ISSUE THREAD

**Issue by qazljlj** [AschPlatform/asch#63]
init文件中通过app.setDefaultFee()设置了最低手续费，然后合约事务unsigned接口手续费fee字段的值比默认手续费更低 合约也能执行成功

**Comment by sqfasd** [comment]
![image](https://user-images.githubusercontent.com/2252162/35140698-30a4a80e-fd33-11e7-8abf-eb52782e557c.png)
@qazljlj 请问能重现吗，我试了，fee小于最低手续费的时候，会返回错误的
