### ISSUE TITLE
readme和代码注释尽量用英文？

### ISSUE THREAD

**Issue by yanyiwu** [AschPlatform/asch#71]
毕竟我们可是要走出国门的，是不是尽量不要在Readme或者类似地方写中文呢？尽量统一用英文。
以开发者的角度，看到全英文的项目总会觉得更专业一点，毕竟面向的全球的开发者。
哪怕写蹩脚一点的英文都无所谓的。

毕竟，我听说咱们可是要搞global开发者大赛的？

**Comment by sqfasd** [comment]
@ByCnck 把readme里的中文去掉吧

**Comment by yanyiwu** [comment]
https://github.com/AschPlatform/asch/pull/79 @sqfasd @ByCnck 我先merge了。也把这个issue close了，感觉一个issue放着太多天没处理。。也不太好。我先处理了。
