### ISSUE TITLE
asch.io 域名在微信中打不开，有什么办法呢，备案可以解决吗？

### ISSUE THREAD

**Issue by yanyiwu** [AschPlatform/asch#74]
域名在微信打不开是硬伤啊，虽然可以用浏览器打开，但是微信中打不开，对文章的传播就打折扣了，尤其是社区论坛 bbs.asch.io 。有啥办法解决么

**Comment by liangpeili** [comment]
asch.io国内无法备案， 只能使用其他已备案域名比如asch.cn

**Comment by yanyiwu** [comment]
那目前解决微信打开分享被封的问题主要得靠asch.cn 了？但是看现在的 bbs.asch.cn 并没法打开？

**Comment by yanyiwu** [comment]
目前来看，微信已经可以打开了。先 close 了，不过具体原因可以谁可以告知一下吗？不会真的是封禁久了就自动解封了吧？

**Comment by liangpeili** [comment]
技术上没有操作，难道是大家的申诉起作用了？
