### ISSUE TITLE
时间差经常提示需要校准的问题可以自动解决吧？无需用户手动校准吧？

### ISSUE THREAD

**Issue by yanyiwu** [AschPlatform/asch#81]
![5 31e3a m7uxfz3t kkm](https://user-images.githubusercontent.com/2162645/34527963-4d55ac1c-f0e2-11e7-8d08-0270524a55ab.jpg)

我的理解这个是普遍现象吧，至少我就经常遇到。

是不是可以自动通过程序解决呢？

在浏览器第一次打开的时候，获取服务器的时间A和本地客户端的时间B，算出时间差 C=A-B
然后再每次需要使用到本地时间的时候，不使用B，而是使用 B+C 作为校准后的本地时间来用。

这样我的理解就是自动彻底解决钱包时间差的问题吧？

而不是现在每次都要提示用户手动校准。。。我天天被提示手动校准。感觉用户体验不好啊。

**Comment by eagleHovering** [comment]
@lbgod2222 可把时间放宽到30min，如果时间相差过大最好谨慎处理。
@yanyiwu 系统中已经有这样的策略

**Comment by yanyiwu** [comment]
好的，超过30min 应该就好很多了。

**Comment by lbgod2222** [comment]
已改为 30 min

**Comment by yanyiwu** [comment]
求抓紧上线到 wallet.asch.cn和wallet.asch.io吧
