### ISSUE TITLE
利用asch-cli dapps -a创建dapp时出现错误

### ISSUE THREAD

**Issue by Rainlin007** [AschPlatform/asch#90]
我们团队目前正在asch上做dapp的开发，但创建dapp时出现错误，
错误发生在使用asch-cli dapps -a建立dapp模板时，
当输入完图标网址icon后，便thr
ow error，希望官方修复下
![2018-01-19_13-03-41](https://user-images.githubusercontent.com/23253008/35136013-d475723c-fd1b-11e7-808f-ffabb282d48c.png)

**Comment by sqfasd** [comment]
请使用最新版本的```asch-cli```
```npm install asch-cli@latest ```
或者
```npm install asch-cli@1.3.7```

**Comment by Rainlin007** [comment]
## 回复
ok，应该是1.3.8，另外你们的docker应该更新下，我就是在docker里装的，还有我看asch-cli下面的issure有同样的问题，可以回复下，另外，提交个小问题

## 小问题
这个包里面https://www.asch.io/downloads/asch-linux-latest-testnet.tar.gz的
aschd文件的`ismainnet()`函数下面有点错误

![2018-01-19_14-02-27](https://user-images.githubusercontent.com/23253008/35136996-df9ddfcc-fd21-11e7-9a2e-c6db6a9bcc2b.png)

判断两个均为mainnet，前者应为testnet
不过这个本身就是mainnet的包，也不影响使用，简单提下

**Comment by sqfasd** [comment]
好的，这个问题是打包的时候造成的。脚本里面默认是testnet，打包成mainnet的时候，会把所有的testnet替换成mainnet，所以这个地方本来是不需要判断的，打包的时候就会决定是miannet还是testnet的
@ByCnck 去掉这个判断逻辑吧，让gulp来判断

**Comment by ByCnck** [comment]
https://github.com/AschPlatform/asch/commit/c32b1de063ace4cfe7155d30fd3a6860f28e2b0a
