### ISSUE TITLE
注册dapp后，显示DApp not found

### ISSUE THREAD

**Issue by Rainlin007** [AschPlatform/asch#92]
在local链中注册dapp后，仍显示not found

![2018-01-19_19-35-31](https://user-images.githubusercontent.com/23253008/35149394-e00c0ca2-fd50-11e7-9fb7-a508e36d9fef.png)
![2018-01-19_19-33-05](https://user-images.githubusercontent.com/23253008/35149400-e4a70244-fd50-11e7-8a21-2d13517b9d1f.png)

**Comment by Rainlin007** [comment]
按照官方的hello-wolrd教程，再用asch-cli 注册dapp后，仍显示not found ,再次注册显示已存在

**Comment by liangpeili** [comment]
注册完dapp后是否重启了aschd？ `aschd restart`

**Comment by ByCnck** [comment]
localnet放到公网时，可能会触发一个bug：可能会读取到tesnet的数据，这是由于前端代码自动选择最优节点导致的，可以进浏览器调试默认，看返回的结果的服务器ip是不是kjr5.com。

最好的方式是在localnet本地确认dapp是否注册成功：
curl -k -H "Content-Type: application/json" -X GET http://localhost:4096/api/dapps/yourDappId/blocks/height && echo
