### ISSUE TITLE
Server error: Insufficient balance: A4hSa28WuATzkRiFDCsSpE8yvG9Py73uD1

### ISSUE THREAD

**Issue by a1300** [AschPlatform/asch#93]
Dear Asch-Team,

I want to develop a dapp on the localnet. I ran into some problems. I need your help. I followed these steps:
https://github.com/a1300/asch-dapps/blob/master/getting-started.md

I called ```../../asch-cli/bin/asch-cli -H 127.0.0.1 registerdapp --metafile dapp.json --secret "fall destroy discover turkey bronze smooth web grass slide vote wise sustain"```
I get the error ```Server error: Insufficient balance: A4hSa28WuATzkRiFDCsSpE8yvG9Py73uD1```

My local account (A4hSa28WuATzkRiFDCsSpE8yvG9Py73uD1) has an **unconfirmed balance** of 70000000. I checked my balance with following code: 
```../../asch-cli/bin/asch-cli -H 127.0.0.1 openaccount "fall destroy discover turkey bronze smooth web grass slide vote wise sustain"```

1. What am I doing wrong? 
2. How can I confirm my balance on my account?
3. What are the exact steps to get a dapp on the localnet running? (the documentation is currently not really helpful. When I manage to get a dapp up and running I will update the documentation accordingly :-) )

Thanks in advance!

**Comment by liangpeili** [comment]
@a1300 Did your localnet running normal? I will revise the docs tomorrow.

**Comment by a1300** [comment]
@liangpeili  Yes, everything runs normal. Do I need to have a second node running to confirm my money-transaction?

**Comment by liangpeili** [comment]
@a1300  One localnet node is enough. Did you configure the frontend? How about login in from the frontend?

**Comment by a1300** [comment]
@liangpeili Yes, the frontend works. I can also login into the frontend.

**Comment by liangpeili** [comment]
@a1300 When you use `asch-cli openaccount`  or `asch-cli getbalance` to check an address's balance, The balance is displayed in minimal precision.  It means your balance 70000000 is 0.7XAS (XAS has a precision of 8).  It takes 100 XAS to register a dapp, so the error is 'Insufficient balance'

**Comment by a1300** [comment]
Thank you! :-) 
I registered successfully the dapp. Now I am fighting to install it :-)
