### ISSUE TITLE
Dapps: Masteraccount for localnet development? (help wanted)

### ISSUE THREAD

**Issue by a1300** [AschPlatform/asch#99]
Dear Asch-Team,

I have a question regarding the **master account** for the localnet development:

The account **14762548536863074694** has 100000000 XAS. Does someone know the secret to this account?

So far I collected the block-rewards of the delegates to get the 100 XAS to register a dapp. I hoped that this process could be easier.

Thanks in advance!
Kind regards
a1300

**Comment by liangpeili** [comment]
```
// This is the genesis account of localnet and one hundred million XAS in it.
{
  "keypair": {
    "publicKey": "8065a105c785a08757727fded3a06f8f312e73ad40f1f3502e0232ea42e67efd",
    "privateKey": "a64af28537545301f66579604628b55c7a7a102752bbd8f0b0d152f9754e78d58065a105c785a08757727fded3a06f8f312e73ad40f1f3502e0232ea42e67efd"
  },
  "address": "14762548536863074694",
  "secret": "someone manual strong movie roof episode eight spatial brown soldier soup motor" // password
}
```

**Comment by a1300** [comment]
Thank you!! :-)
